DROP TABLE IF EXISTS `items`;
CREATE TABLE `items` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `PARENT_ID` INT(20),
  `TITLE` VARCHAR(50) NOT NULL,
  `DESCRIPTION` VARCHAR(255),
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
